# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 454186498ed9146aebd201de47c40fc1f1e11ec842ca6ce58399ef73cf78641965c4e7e0873077418e2ff11a31021f2bbee22e782c27cd1ebf58e386255b8f01

test:
  secret_key_base: 0060aaa89dbfcf32116e77a6854c6eb06157441fb75c10ecff47b7681e60bf459bcb3707bf04e6bf8c9c71bf222720aeaf77c0872b82ce7ecc9785a5604b6cb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
